# Generated by Django 4.1.5 on 2024-07-13 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_rename_contact_us_contact_us_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_page',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
