# Generated by Django 4.1.5 on 2024-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_contact_us_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us_page',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
