# Generated by Django 4.1.5 on 2024-07-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_alter_contact_us_page_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_page',
            name='date',
        ),
    ]
