# Generated by Django 4.1.5 on 2024-06-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Videos',
        ),
    ]
