# Generated by Django 4.1.5 on 2024-06-14 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_app',
            name='user',
        ),
        migrations.AddField(
            model_name='chat_app',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat_app',
            name='text',
            field=models.TextField(blank=True, default='no content', null=True),
        ),
    ]
