# Generated by Django 4.1.5 on 2024-06-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0005_remove_order2_title_remove_order2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='abstract',
            field=models.FileField(upload_to='media/'),
        ),
    ]
