# Generated by Django 4.1.5 on 2024-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0008_alter_order2_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('title', models.CharField(default='not given', max_length=200)),
                ('number_of_pages', models.IntegerField()),
                ('deadline', models.DateTimeField(max_length=100)),
                ('abstract', models.FileField(upload_to='abstract/')),
                ('description', models.TextField()),
                ('accept_terms', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order2',
            new_name='Research',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
