# Generated by Django 4.1.5 on 2024-06-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0009_thesis_rename_order2_research_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsDesignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('service', models.CharField(choices=[('logo', 'Logo'), ('photo_editing', 'Photo Editing'), ('banner', 'Banner'), ('birth_certificate', 'Birth Certificate'), ('wedding_card', 'Wedding Card'), ('business_card', 'Business Card'), ('poster', 'Poster'), ('advertisement', 'Advertisement'), ('presentation_template', 'Presentation Template')], max_length=50)),
                ('deadline', models.DateTimeField()),
                ('design_file', models.FileField(upload_to='designs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('accept_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.FileField(upload_to='Thesis/'),
        ),
    ]
