# Generated by Django 4.1.5 on 2024-06-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0013_alter_programmingprojectsubmission_specific_work_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('video_length', models.CharField(max_length=50)),
                ('video_format', models.CharField(choices=[('wave', 'WAVE'), ('mp4', 'MP4'), ('mov', 'MOV'), ('avi', 'AVI'), ('mkv', 'MKV')], max_length=10)),
                ('deadline', models.DateTimeField()),
                ('project_file', models.FileField(upload_to='projects/')),
                ('description', models.TextField(blank=True, null=True)),
                ('accept_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='programmingprojectsubmission',
            name='specific_work_area',
            field=models.CharField(choices=[('website', 'Website'), ('app', 'App'), ('desktop', 'Desktop'), ('game', 'Game'), ('other', 'Other')], max_length=50),
        ),
    ]
