# Generated by Django 4.1.5 on 2024-06-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0015_alter_videoeditingsubmission_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('accept_terms', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('source_language', models.CharField(max_length=100)),
                ('target_language', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
