# Generated by Django 4.1.5 on 2024-07-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0018_assignment_status_assignment_use_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='business_plan',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='graphicsdesignsubmission',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='programmingprojectsubmission',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='thesis',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='transcription',
            old_name='use_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='videoeditingsubmission',
            old_name='use_name',
            new_name='user_name',
        ),
    ]
