# Generated by Django 4.1.5 on 2024-06-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_contact_us_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='Subject',
            field=models.TextField(default='defualt'),
            preserve_default=False,
        ),
    ]
