# Generated by Django 4.1.5 on 2024-06-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_remove_contact_us_phone_contact_us_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact_us_page',
        ),
    ]
