# Generated by Django 4.1.5 on 2024-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0004_alter_order2_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user',
        ),
        migrations.AddField(
            model_name='order2',
            name='accept_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order2',
            name='abstract',
            field=models.FileField(upload_to='abstracts/'),
        ),
        migrations.AlterField(
            model_name='order2',
            name='deadline',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order2',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order2',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order2',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='order2',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order2',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='order2',
            name='title',
            field=models.CharField(default='not given', max_length=200),
        ),
    ]
