# Generated by Django 4.1.5 on 2024-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0006_alter_order2_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='abstract',
            field=models.FileField(upload_to='Research/'),
        ),
    ]
