# Generated by Django 4.1.5 on 2024-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0012_alter_programmingprojectsubmission_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingprojectsubmission',
            name='specific_work_area',
            field=models.CharField(choices=[('website', 'Website'), ('app', 'App'), ('desktop', 'Desktop'), ('game', 'Game'), ('other', 'Other')], default='null', max_length=50),
        ),
    ]
