# Generated by Django 4.1.5 on 2024-06-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0014_videoeditingsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoeditingsubmission',
            name='project_file',
            field=models.FileField(upload_to='video_editing/'),
        ),
    ]
